services:
  jv-idx-mcp:
    container_name: jv-idx-mcp
    image: jv-idx-mcp:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - MCP_API_KEY=${MCP_API_KEY:-}
    ports:
      - "8000:8000"
